# action.yml
name: 'EKSCtl Kale'
description: 'EKSCtl Kale pipeline compiler for notebooks'
inputs:
  awsAccessKeyId:
    description: 'awsAccessKeyId'
    required: true
  awsSecretAccessKey:
    description: 'awsSecretAccessKey'
    required: true
  region:
    description: 'AWS default region'
    required: false
    default: 'us-west-1'
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.awsAccessKeyId }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.awsSecretAccessKey }}
    AWS_DEFAULT_REGION: ${{ inputs.region }}
