# action.yml
name: 'EKSCtl Kale'
description: 'EKSCtl Kale pipeline compiler for notebooks'
inputs:
  region:
    description: 'AWS default region'
    required: false
    default: 'us-west-1'
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ inputs.region }}
